# Generated by Django 5.1.6 on 2025-03-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.SmallIntegerField(choices=[(0, 'Administrator'), (1, 'Customer'), (2, 'Vendor')], default=1),
        ),
    ]
